id: I9F442495
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T02:05:01+00:00'
last_modified: '2022-06-08T03:15:24.373161+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ1022
  title: བསོད་ནམས་རྩེ་མོའི་གསུང་འབུམ་ཐོར་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F1A9:
      image_group_id: I1KG13506
      title: ''
      total_pages: 678
      order: 1
      base_file: F1A9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
